### ISSUE TITLE
[ADD PACKAGE] group-track-flutter

### ISSUE THREAD

**Issue by cp-ishita-g** [fluttergems/awesome-open-source-flutter-apps#664]
From handling real-time updates to managing background tracking, GroupTrack simplifies these challenges for Flutter apps. It streamlines location updates, geofencing, and state management, saving time and effort while ensuring optimal performance.

- group-track-flutter
- [It's pub URL](https://github.com/canopas/group-track-flutter/pulls) 
- travel and navigation
- Enhancing family safety and communication with real-time location sharing

**Comment by ashitaprasad** [comment]
@cp-ishita-g You can raise a PR by following our [CONTRIBUTING GUIDE](https://github.com/fluttergems/awesome-open-source-flutter-apps/blob/main/CONTRIBUTING.md)
Thanks!

**Comment by ashitaprasad** [comment]
Hi @cp-ishita-g, Only for adding a package you have to create an issue. Since this is not a package but an open source app, I transferred the issue to this repository.
For adding the open source app, you have to create a PR and add the open source app name, it's link along with a short description. More details can be found in the [contributing guide](https://github.com/fluttergems/awesome-open-source-flutter-apps/blob/main/CONTRIBUTING.md)

Please feel free to reach out in case you have any issues.
Thanks!

**Comment by cp-ishita-g** [comment]
Thank you for your deep explanation, according to the guide i have created the fork and in that add change and create pull request can you please review it and merge it 
[pull request](https://github.com/cp-ishita-g/awesome-open-source-flutter-apps/pull/1)

**Comment by ashitaprasad** [comment]
@cp-ishita-g You have to make edits in the fork and make a pull request to this repo.
You have opened a PR in your own repo. Please rectify the issue.
